### ISSUE TITLE
Zpětná vazba.

### ISSUE THREAD

**Issue by IxAriela** [KristynaSodomkova/1---stan_se_koderkou_cv#1]
Ahoj,

Líbí se mi, že sis tam zkoušela i responsiv a media queries, i když jsi nemusela :) Taky je super ta css animace textu :)

Zkus udržovat čistý kód, tj. nemít tam zbytečné styly, které nepoužíváš, u tebe například ul. Navíc zrovna u tohoto je flex-direction, ale není tam určení display: flex;, takže taky úplně zbytečný řádek. A dávat k ul obecně list-style: none; taky nebývá úplně žádoucí, to chceš spíše ke konkrétnímu seznamu (například použití v menu), ale potom v obyčejném textu by ti to mohlo chybět. K čistotě patří i zakomentované kusy kódu. Pokud to tam nemáme z důvodu budoucího konkrétního použití, neměl by tam zakomentovaný kód vůbec být. Tady přivřu oko, pokud si ho tam chceš pro sebe nechat, ale nemělo by se to takto nikomu předávat.

Zkus taky dávat k sobě styly jednoho prvku. Například "a" a "a:hover" je dobré mít pod sebou, ať hned vidíš oboje a není třeba to dohledávat.

Taky doporučuji využívat position: absolute co nejméně. Nejde se tomu vyhnout úplně, ale pokud to jde, zkusit to. Pak se to hodí u responsivu, protože position absolute ti překryje to co máš relativně, zatímco pokud jsou oba prvky relativně, tak se ten druhý hodí na další řádek. Máš toho hodně v .basic-info, na odstranění by to chtělo víc překopat i html. Dala bych tam 2 obaly - text a obrázek. Text by se pak dále členil na name, presentation (width 100%) a buttons (float left) a side-bar (float right, oboje třeba width 45%, samozřejmě je pak potřebo všude kde je float dát clear: both), případně flexem. Toto po tobě nebudu chtít přepracovat, jen kdyby sis to chtěla zkusit :)

 Proč máš vlastně buttons v presentation? Nemá to nic společného, mělo by to být zvlášť.

U .profpic máš height: auto;, ale pak máš obrázek uvnitř absolutně. Takže height: auto je vlastně 0. Do budoucna by bylo fajn si to hlídat, dobře se to dělá přes Chrome Dev tools, když najedeš na sbalený div, tak by se ti měl zvýraznit, kde je. Pokud ho nenajdeš, tak je to (většinou) špatně a může ti to dělat problémy třeba při responsivu. Dev tools jsi ještě neznala, takže toto opět nebudu chtít opravit :)

Když je display: flex na obalu, nepřenese se to automaticky na prvky uvnitř. Tedy dávat nějaké upřesnění flexu na vnitřní prvek je zbytečné, nebude fungovat. Na zápatí vůbec flex nepotřebuješ, stačí ti to zarovnání doprostřed a pokud bys chtěla, doporučila bych spíš padding nahoře a dole.

Side-bar  a jeho height: 100vh ti tam dělá tu obří mezeru ještě pod zápatím. Toto prosím taky oprav. vh je Viewport Height, tedy výška kterou vidíš, výška monitoru. To většinou moc používat nechceš :)

Budu chtít opravit toto:

- [x] čistý kód (v podstatě stačí odstranit ul)
- [x] dát pryč .buttons z .presentation a samozřejmě by to mělo stále fungovat
- [x] opravit patičku
- [x] opravit obří mezeru pod obsahem

**Comment by IxAriela** [comment]
Mám ještě pár drobností, které jsou ale často individuální nebo to jsou jen nepsaná pravidla.

Zkus co nejvíce sjednotit jednotky. Každé se hodí na něco, takže se to nikdy nepovede 100%. Třeba mít stejné jednotky na mezery (padding, margin) a velikost textu. Já na oboje používám nejvíc rem. % se hodí na šířkové prvky kvůli responsivu. A bohužel i px se občas hodí, třeba na mini ikonky soc sítí, které nebudou nikdy měnit svoji velikost. Ale líbilo by se mi mít aspoň ty mezery a písmo stejnou jednotkou (není nutné, to je asi spíš jen moje preference) :)

Hover se používá na odkazy a na prvky, se kterými jde nějak interagovat, právě aby se zvýraznila ta interakce. Používat ho tedy na prvky, které jsou čistě textové může být dost matoucí. Na tvé stránce bych čekala hover na obou buttonech, na všech soc. síťových tlačítkách a v menu. Ale ne na celé záhlaví nebo odstavce textu. A pokud už je takto využit, tak při členění na 3 sloupce bych ho očekávala na každém sloupci zvlášť.

**Comment by KristynaSodomkova** [comment]
Ahoj, mám trochu problém splnit jedenu opravu, odstranila jsem ul a všechny ty zakomentovaný kusy kódu, přendala buttons, opravila patičku, ale kde najdu tu mezeru pod obsahem? Když si to zobrazím v devtools na užším ani širším displej se mi tam nikde žádná neukazuje :/ Můžeš prosím poslat printscreen? (Přiznávám, nepočítala jsem s kontrolou kódu, myslela jsem, že to bude jen jako experiment pro nás a něco na ukázku pro vás, proto jsem ani nedodělávala responzivitu, jen jsem tam vložila příklad použití).
![Uploading Snímek obrazovky pořízený 2022-09-19 22-27-47.png…]()

**Comment by KristynaSodomkova** [comment]
Hotovo, obří mezera odstraněna!
